export const ADMIN_HOME_PAGE = "/admin"
export const ADMIN_PRODUCTS = ADMIN_HOME_PAGE + "/products";
export const CREATE_PRODUCT = ADMIN_PRODUCTS + "/create"
export const EDIT_PRODUCT = ADMIN_PRODUCTS + "/edit"
export const ADMIN_LOGIN = ADMIN_HOME_PAGE + "/login"
export const NOT_FOUND = "/page-not-found"
export const REPORT = ADMIN_HOME_PAGE + "/report"

export const HOME = "/"
export const USER_PRODUCTS = "/products"
export const CART = "/cart"
export const CONTACT = "/contact"
export const ABOUT = "/about"
export const FAQ = "/faq"
export const REGISTER = "/register"
export const LOGIN = "/login"
export const ORDER = "/order"